language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .
  - pip install -r dev-requirements.txt
  - pip install -r doc-requirements.txt

script:
  - ci/lint.sh
  - pytest --cov . --cov-report term
  - mkdocs build
