site_name: Tanker documentation

theme:
  name: readthedocs
  custom_dir: custom_theme

extra_css: [extra.css]
strict: true

markdown_extensions:
  - markdown.extensions.admonition #for !!! notice
  - markdown.extensions.def_list

  - toc:
      permalink: True
      separator: "_"

pages:
- Home: index.md

- Getting started:
  - Basic usage: guide/basics.md
  - Handling GitLab merge requests: guide/merge_requests.md


- Reference:
  - Comand line usage: ref/cli.md
  - Configuration files formats: ref/formats.md

- Contributing: contrib.md

- FAQ: faq.md

- Changelog: changelog.md
