name: linters

on: [push]

jobs:
  run_linters:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Prepare project for development
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.create false
        python -m poetry install

    - name: Run black
      run: |
        poetry run black --check .

    - name: Run mypy
      run: |
        MYPYPATH=stubs poetry run mypy tsrc

    - name: Run flake8
      run: |
        poetry run flake8 .
